### ISSUE TITLE
npm package is not found

### ISSUE THREAD

**Issue by disestevez** [aave/aave-v3-core#623]
It seems like the npm package is not found: https://www.npmjs.com/package/@aave/aave-v3-core returns a 404 error.
This is further confirmed by calling `npm install @aave/aave-v3-core`, which also returns a 404 error.

**Comment by kartojal** [comment]
Check again!

https://www.npmjs.com/package/@aave/aave-v3-core

**Comment by disestevez** [comment]
It seems that there are still issues with npm. When `npm install @aave/core-v3` is executed, the console gives the following error: 
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@aave%2fdeploy-v3 - Not found
npm ERR! 404  '@aave/deploy-v3@^1.17.0' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

Do you have any idea?

**Comment by disestevez** [comment]
This is further confirmed by going to the dependencies page of `@aave/core-v3`, found at https://www.npmjs.com/package/@aave/core-v3, which shows `@aave/deploy-v3`. However, https://www.npmjs.com/package/@aave/deploy-v3 gives a 404 error :(
