### ISSUE TITLE
Inconsistent naming of reservesData mapping and reservesList

### ISSUE THREAD

**Issue by LHerskind** [aave/aave-v3-core#634]
**Identified by**:
Aave

**Scope**:
The naming of the reserves data mapping when passed to libraries is inconsistent and uses both `reserves` and `reservesData`
The naming of the reservesList mapping when passed to libraries is inconsistent and uses both `reserves` and `reservesList` 
Together, this can be confusing for the reader as `reserves` don't consistently point to the list or data. 

**Suggestion**:
Always use `reservesData` for the data mapping and `reservesList` for the list.

**Comment by miguelmtzinf** [comment]
There is one outstanding renaming in `PoolLogic.sol`
