### ISSUE TITLE
[Dev Docs] Typo: `Pool.getReserveList` => `Pool.getReservesList`

### ISSUE THREAD

**Issue by visvirial** [aave/aave-v3-core#661]
I find a typo in the developer doc at https://docs.aave.com/developers/core-contracts/pool#getreservelist .
I'm writing this issue (instead of sending a PR) since I couldn't find the source code repo of the documentation.
Please fix it.

**Comment by The-3D** [comment]
thanks - we will make the docs repo public as well.

**Comment by visvirial** [comment]
Thank you for your reply!

Oh, the doc is not public,,, that's why I couldn't find the repo. lol

It seems the doc is not fixed yet. Will it be fixed soon?
I'm just confirming that this issue will not be forgot.
