### ISSUE TITLE
Discussion: Aave v2 to v3 migration

### ISSUE THREAD

**Issue by chriscrutt** [aave/aave-v3-core#674]
**Migrate Aave v2 positions to Aave v3**

Right now InstaDapp allows you to migrate your Aave v2 position (both deposits and borrows) to v3. The caveat is that you can only do it if you move your positions to their platform/a smart contract. If you wish to withdraw back to your wallet you’re required to pay back all your loans :(

It would be nice if Aave implemented an easy way to migrate positions from v2 to v3 on its website while keeping your assets in your wallet and not having to liquidate/pay back loans.

As a side note, it would also be cool to have a debt swap function if you'd like to swap from one stablecoin to another without repaying loans. I know InstaDapp has a collateral/debt swap function too.

**Comment by chriscrutt** [comment]
Maybe more applicable to post in [interface](https://github.com/aave/interface) repo lemme know

**Comment by kartojal** [comment]
Yes! I think this would make sense at interface repository

**Comment by chriscrutt** [comment]
added it here https://github.com/aave/interface/issues/681 :)
