### ISSUE TITLE
Pool decimals

### ISSUE THREAD

**Issue by andreariba** [aave/aave-v3-core#676]
I'm trying to get the user data from an aave v3 contract and I'm very confused by the number of decimals, or better I cannot find the number of decimals with which the collateral, borrowable and debt are returned. By doing some test it looks the Pool on rinkeby (0xBA6378f1c1D046e9EB0F538560BA7558546edF3C) returns ETH with 12 decimals I was expecting something like 18 ... 
Can anybody help with that? shouldn't a getDecimals() be available somehow? Thanks

**Comment by miguelmtzinf** [comment]
@andreariba which function or data you want to fetch?
There is not decimals for Pool. Every piece of data has its own decimals.

**Comment by miguelmtzinf** [comment]
Closing. Feel free to re-open the issue if needed.
