### ISSUE TITLE
Problem with "npm install @aave/core-v3@1.16.0" version

### ISSUE THREAD

**Issue by IoanSolovastru** [aave/aave-v3-core#678]
I tried to use the latest version of aave, so I tried to install the following package:
`npm install @aave/core-v3@1.16.0`
The only version available is **1.13.1**.

Am I doing something wrong or is it a problem with packaging?

**Comment by miguelmtzinf** [comment]
@IoanSolovastru Last version of aave core in npm is 1.13.1
You can check the available versions here: https://www.npmjs.com/package/@aave/core-v3
