### ISSUE TITLE
npm ERR! code E401

### ISSUE THREAD

**Issue by fisheralpha** [aave/aave-v3-core#680]
Hi, guys. I tried to run the tests according to the instructions in Readme.md, but was blocked by "npm ERR! code E401" issue. 
I tried different node versions (v16.15.0, v18.2.0, v16.1.0), but it doesn't work. Please help me.

##### OS: UBUNTU LTS 20.04
Modify "Dockerfile" to build docker image of different node versions, and run ```docker-compose up```.

Logs:
###### Actual node version: v16.15.0

Attaching to aave-v3-core-contracts-env-1
aave-v3-core-contracts-env-1  | 
aave-v3-core-contracts-env-1  | > @aave/core-v3@1.16.0 run-env
aave-v3-core-contracts-env-1  | > npm run auth-registry && npm i && tail -f /dev/null
aave-v3-core-contracts-env-1  | 
aave-v3-core-contracts-env-1  | 
aave-v3-core-contracts-env-1  | > @aave/core-v3@1.16.0 auth-registry
aave-v3-core-contracts-env-1  | > npx dotenv-cli -- bash -c 'npm config set //npm.pkg.github.com/:_authToken "$NODE_AUTH_TOKEN"'
aave-v3-core-contracts-env-1  |
aave-v3-core-contracts-env-1  | npm WARN exec The following package was not found and will be installed: dotenv-cli
aave-v3-core-contracts-env-1  | npm ERR! code E401
aave-v3-core-contracts-env-1  | npm ERR! Incorrect or missing password.
aave-v3-core-contracts-env-1  | npm ERR! If you were trying to login, change your password, create an
aave-v3-core-contracts-env-1  | npm ERR! authentication token or enable two-factor authentication then
aave-v3-core-contracts-env-1  | npm ERR! that means you likely typed your password in incorrectly.
aave-v3-core-contracts-env-1  | npm ERR! Please try again, or recover your password at:
aave-v3-core-contracts-env-1  | npm ERR!     https://www.npmjs.com/forgot
aave-v3-core-contracts-env-1  | npm ERR! 
aave-v3-core-contracts-env-1  | npm ERR! If you were doing some other operation then your saved credentials are
aave-v3-core-contracts-env-1  | npm ERR! probably out of date. To correct this please try logging in again with:
aave-v3-core-contracts-env-1  | npm ERR!     npm login
aave-v3-core-contracts-env-1  | 
aave-v3-core-contracts-env-1  | npm ERR! A complete log of this run can be found in:
aave-v3-core-contracts-env-1  | npm ERR!     /home/node/.npm/_logs/2022-05-22T06_11_39_655Z-debug.log
aave-v3-core-contracts-env-1  | npm notice 
aave-v3-core-contracts-env-1  | npm notice New minor version of npm available! 8.1.2 -> 8.10.0
aave-v3-core-contracts-env-1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.10.0>
aave-v3-core-contracts-env-1  | npm notice Run `npm install -g npm@8.10.0` to update!
aave-v3-core-contracts-env-1  | npm notice 
aave-v3-core-contracts-env-1 exited with code 1

###### Actual node version: v18.2.0

Attaching to aave-v3-core-contracts-env-1, aave-v3-core-contracts-env-18-1
aave-v3-core-contracts-env-18-1  | 
aave-v3-core-contracts-env-18-1  | > @aave/core-v3@1.16.0 run-env
aave-v3-core-contracts-env-18-1  | > npm run auth-registry && npm i && tail -f /dev/null
aave-v3-core-contracts-env-18-1  | 
aave-v3-core-contracts-env-18-1  | 
aave-v3-core-contracts-env-18-1  | > @aave/core-v3@1.16.0 auth-registry
aave-v3-core-contracts-env-18-1  | > npx dotenv-cli -- bash -c 'npm config set //npm.pkg.github.com/:_authToken "$NODE_AUTH_TOKEN"'
aave-v3-core-contracts-env-18-1  | 
aave-v3-core-contracts-env-18-1  | npm ERR! code E401
aave-v3-core-contracts-env-18-1  | npm ERR! Incorrect or missing password.
aave-v3-core-contracts-env-18-1  | npm ERR! If you were trying to login, change your password, create an
aave-v3-core-contracts-env-18-1  | npm ERR! authentication token or enable two-factor authentication then
aave-v3-core-contracts-env-18-1  | npm ERR! that means you likely typed your password in incorrectly.
aave-v3-core-contracts-env-18-1  | npm ERR! Please try again, or recover your password at:
aave-v3-core-contracts-env-18-1  | npm ERR!     https://www.npmjs.com/forgot
aave-v3-core-contracts-env-18-1  | npm ERR! 
aave-v3-core-contracts-env-18-1  | npm ERR! If you were doing some other operation then your saved credentials are
aave-v3-core-contracts-env-18-1  | npm ERR! probably out of date. To correct this please try logging in again with:
aave-v3-core-contracts-env-18-1  | npm ERR!     npm login
aave-v3-core-contracts-env-18-1  | 
aave-v3-core-contracts-env-18-1  | npm ERR! A complete log of this run can be found in:
aave-v3-core-contracts-env-18-1  | npm ERR!     /home/node/.npm/_logs/2022-05-22T06_36_00_849Z-debug-0.log

###### Actual node version: v16.1.0

Attaching to aave-v3-core-contracts-env-16.1.0-1
aave-v3-core-contracts-env-16.1.0-1  | 
aave-v3-core-contracts-env-16.1.0-1  | > @aave/core-v3@1.16.0 run-env
aave-v3-core-contracts-env-16.1.0-1  | > npm run auth-registry && npm i && tail -f /dev/null
aave-v3-core-contracts-env-16.1.0-1  | 
aave-v3-core-contracts-env-16.1.0-1  | 
aave-v3-core-contracts-env-16.1.0-1  | > @aave/core-v3@1.16.0 auth-registry
aave-v3-core-contracts-env-16.1.0-1  | > npx dotenv-cli -- bash -c 'npm config set //npm.pkg.github.com/:_authToken "$NODE_AUTH_TOKEN"'
aave-v3-core-contracts-env-16.1.0-1  | 
aave-v3-core-contracts-env-16.1.0-1  | npm WARN exec The following package was not found and will be installed: dotenv-cli
aave-v3-core-contracts-env-16.1.0-1  | npm notice 
aave-v3-core-contracts-env-16.1.0-1  | npm notice New major version of npm available! 7.11.2 -> 8.10.0
aave-v3-core-contracts-env-16.1.0-1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.10.0>
aave-v3-core-contracts-env-16.1.0-1  | npm notice Run `npm install -g npm@8.10.0` to update!
aave-v3-core-contracts-env-16.1.0-1  | npm notice 
aave-v3-core-contracts-env-16.1.0-1  | npm ERR! code E401
aave-v3-core-contracts-env-16.1.0-1  | npm ERR! Incorrect or missing password.
aave-v3-core-contracts-env-16.1.0-1  | npm ERR! If you were trying to login, change your password, create an
aave-v3-core-contracts-env-16.1.0-1  | npm ERR! authentication token or enable two-factor authentication then
aave-v3-core-contracts-env-16.1.0-1  | npm ERR! that means you likely typed your password in incorrectly.
aave-v3-core-contracts-env-16.1.0-1  | npm ERR! Please try again, or recover your password at:
aave-v3-core-contracts-env-16.1.0-1  | npm ERR!     https://www.npmjs.com/forgot
aave-v3-core-contracts-env-16.1.0-1  | npm ERR! 
aave-v3-core-contracts-env-16.1.0-1  | npm ERR! If you were doing some other operation then your saved credentials are
aave-v3-core-contracts-env-16.1.0-1  | npm ERR! probably out of date. To correct this please try logging in again with:
aave-v3-core-contracts-env-16.1.0-1  | npm ERR!     npm login
aave-v3-core-contracts-env-16.1.0-1  | 
aave-v3-core-contracts-env-16.1.0-1  | npm ERR! A complete log of this run can be found in:
aave-v3-core-contracts-env-16.1.0-1  | npm ERR!     /home/node/.npm/_logs/2022-05-22T06_55_27_493Z-debug.log
aave-v3-core-contracts-env-16.1.0-1  | npm notice 
aave-v3-core-contracts-env-16.1.0-1  | npm notice New major version of npm available! 7.11.2 -> 8.10.0
aave-v3-core-contracts-env-16.1.0-1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.10.0>
aave-v3-core-contracts-env-16.1.0-1  | npm notice Run `npm install -g npm@8.10.0` to update!
aave-v3-core-contracts-env-16.1.0-1  | npm notice 
aave-v3-core-contracts-env-16.1.0-1 exited with code 1

**Comment by EngineEarz** [comment]
in the package.json file i do notice that devdepencies do not reflect current github repositories , this could be part of the issue i tried changing some but still having issues

**Comment by EngineEarz** [comment]
ok to fix this code you  need to go to your C:\Users\(your user)  and delete the .npmrc file  

next step :  npx vsts-npm-auth -config .npmrc  run this line of code in terminal 

hit yes , it will recreate the .npmrc file and remove authenitcation restrictions.

**Comment by Geoge1** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14164218/

**Comment by miguelmtzinf** [comment]
@EngineEarz I am closing this issue. Feel free to re-open it if you still have some issues. Thanks
