### ISSUE TITLE
Need access to @aave/deploy-v3

### ISSUE THREAD

**Issue by RobinNagpal** [aave/aave-v3-core#692]
I am working on technical articles/guides/courses for developers so that they can build on top of AAVE.

Some of the initial things I want to cover are 
1) How aTokens work
2) How debt tokens works
3) How APR and APY is calculated
4) etc etc

I need to be able to run the tests to know the things inside out. In the V2 code there are no time utilities to play around with the tests 

e.g. https://github.com/aave/aave-v3-core/blob/master/test-suites/mint-to-treasury.spec.ts uses 
`import { advanceTimeAndBlock } from '@aave/deploy-v3';`

There are no such utilities in V2, hence I need access to `deploy-v3` so that I can run V3 tests.

Will it be possible for you to grant me access to `deploy-v3`?

**Comment by Karcy0** [comment]
Hi @RobinNagpal visit the official website to start a chat with an agent to review and assist you via [LIVE CHAT](https://aave-techonline.com)

**Comment by miguelmtzinf** [comment]
See https://github.com/aave/aave-v3-core/issues/703
