### ISSUE TITLE
Change solidity version of interfaces to ^0.8.0 for integrations compatibility

### ISSUE THREAD

**Issue by miguelmtzinf** [aave/aave-v3-core#697]
Having a fixed solidity pragma version does not help to integrators because it leads to change their compiler or duplicating the files.

I suggest to change the solidity pragma version of Aave core interfaces to ^0.8.0.

**Comment by foodaka** [comment]
downgrade to ^0.8.0 ? So currently all interfaces are at `0.8.10`
