### ISSUE TITLE
Difference interest formula in normalized value calculation?

### ISSUE THREAD

**Issue by anhthii** [aave/aave-v3-core#702]
I wonder why `getNormalizedIncome` uses `calculateLinearInterest` but `getNormalizedDebt` uses `calculateCompoundedInterest`?
Any one know this? Thank you

**Comment by miguelmtzinf** [comment]
@anhthii It's because the interest is linear in the supply side and compounded in the debt side.

**Comment by nzhl** [comment]
@miguelmtzinf  So Where did the extra compounding interest part go?

**Comment by miguelmtzinf** [comment]
>  @miguelmtzinf  So Where did the extra compounding interest part go?

I responded in your issue!
