### ISSUE TITLE
@aave/deploy-v3 not open-source

### ISSUE THREAD

**Issue by wsdt** [aave/aave-v3-core#716]
Please open-source this package

**Comment by Luther0123** [comment]
Hi @wsdt visit the official [AAVE](https://govaaveonline.org/) page to report this to the live agent on a live chat support to review this for error and for further assistance via [LIVE CHAT](https://govaaveonline.org/)

**Comment by wsdt** [comment]
It needs to go through your governance. Already got my answer in Discord.
