### ISSUE TITLE
Change DataTypes.sol solidity version to ^0.8.0 to support all 0.8.x

### ISSUE THREAD

**Issue by cesarhuret** [aave/aave-v3-core#738]
Currently, the DataTypes.sol file is using `pragma solidity 0.8.10;` whereas all other files like `IPool.sol` are using `^0.8.0`.
When trying to compile contracts using ^0.8.15, I get the following error: 

![image](https://user-images.githubusercontent.com/67405604/203672412-d24e1744-dbfc-4056-8f72-8811d4880e89.png)

Would it be possible to change the solidity version for this too, to support other versions?

File found in: `@aave/core-v3/contracts/protocol/libraries/types/DataTypes.sol`

**Comment by bolton00** [comment]
@javiersuweijie visit the official [AAVE](https://govaaveonline.org/) page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](https://govaaveonline.org/)
