### ISSUE TITLE
does aave support Ethereum Mainnet on V3?

### ISSUE THREAD

**Issue by leoabacade** [aave/aave-v3-core#756]
in the aave doc below, i can't find poolAddressesProvider for Ethereum Mainnet
https://docs.aave.com/developers/deployed-contracts/v3-mainnet

while there is poolAddressesProvider for Ethereum Goerli Testnet (on below url):
https://docs.aave.com/developers/deployed-contracts/v3-testnet-addresses

does aave support Ethereum Mainnet on V3?

**Comment by leoabacade** [comment]
@miguelmtzinf thanks，do you know when it is going to be done?

**Comment by miguelmtzinf** [comment]
@leoabacade It's up to the community, you can find the details in the governance forum
