### ISSUE TITLE
N1: Improved Gas of ScaledBalanceTokenBase::_mintScaled()

### ISSUE THREAD

**Issue by miguelmtzinf** [aave/aave-v3-core#758]
![Screenshot from 2022-12-07 09-52-55](https://user-images.githubusercontent.com/36620902/206132860-9326e6e6-060a-46ec-a5bc-93205ef34f86.png)

**Comment by miguelmtzinf** [comment]
This optimization is being discussed in #707 . This approach is used across the codebase in multiple functions. Changing the approach here, would imply to changing it everywhere and we agreed not to do it for now.

**Comment by eboadom** [comment]
Agree with @miguelmtzinf on this. I think a math refactoring will be done soon, but right now better to not create more asymmetries

**Comment by miguelmtzinf** [comment]
Closing per comments above
