### ISSUE TITLE
Linter auto formatting ReserveLogic against my will

### ISSUE THREAD

**Issue by MichaelMorami** [aave/aave-v3-core#788]
When committing my changes in files other than `ReserveLogic.sol`, the linter forces an auto-format of the file:
<img width="864" alt="Screenshot 2023-01-11 at 13 39 52" src="https://user-images.githubusercontent.com/91594326/211798059-a58735b3-d8ef-4715-b389-d3a40c14bb4a.png">

The changes are introduced in lines 352-355 of the changed files

**Comment by miguelmtzinf** [comment]
Closed by #810
