### ISSUE TITLE
Problem retrieving getPool() address in FlashLoanSimpleReceiverBase.sol contract

### ISSUE THREAD

**Issue by Samboy76** [aave/aave-v3-core#805]
Hello,

When I attempt to access each of the other chains´ PoolAddressesProvider contracts via ethers.getContractAt function as shown in the below code snippet:

```
const PoolAddressesProvider = await hre.ethers.getContractAt("IPoolAddressesProvider", 
    ( chainNetwork == 1 ? web3.utils.toChecksumAddress(addresses.ethereum.routers.aave.poolAddressProvider) :
      chainNetwork == 2 ? web3.utils.toChecksumAddress(addresses.polygon.routers.aave.poolAddressProvider) :
      chainNetwork == 3 ? web3.utils.toChecksumAddress(addresses.avalanche.routers.aave.poolAddressProvider) :
      chainNetwork == 4 ? web3.utils.toChecksumAddress(addresses.arbitrum.routers.aave.poolAddressProvider) :
      web3.utils.toChecksumAddress(addresses.BSC.routers.aave.poolAddressProvider) )
  );
```

It always spits out the following error:

_Error: Transaction reverted: function returned an unexpected amount of data
      at Flashloan.constructor **(@aave/core-v3/contracts/flashloan/base/FlashLoanSimpleReceiverBase.sol:19)**
      at Flashloan.internal@474 (contracts/Flashloan.sol)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)_

Looking at the above line in FlashLoanSimpleReceiverBase.sol from aave v3 core codebase, it refers to the below problematic code line 19 i.e. `getPool()` function as input argument into IPool constructor:

```
constructor(IPoolAddressesProvider provider) {
    ADDRESSES_PROVIDER = provider;
    POOL = IPool(provider.getPool());
  }
```

Please note, this is only an issue with every non-Ethereum chain network as with Ethereum it works perfectly and correctly retrieves getPool address without any issues. Therefore, problem getting it to work with Polygon, Arbitrum and Avalanche.

These are the PoolAddressesProvider contract addresses I am using as inline with aave v3 docs: https://docs.aave.com/developers/deployed-contracts/v3-mainnet

Would appreciate some here as I´m completely stuck here.

Thank you!

**Comment by miguelmtzinf** [comment]
Hey @Samboy76 
The error you are getting seems unrelated to accessing the `PoolAddressesProvider` contract via `ethers`. Which other operation are you doing in your js script?

**Comment by Samboy76** [comment]
It´s the same issue in this other post https://ethereum.stackexchange.com/questions/125062/issue-implementing-and-testing-aave-v3-flash-loan.

**Comment by Samboy76** [comment]
One final point, this issue is with Aave V3 protocol

**Comment by Samboy76** [comment]
@miguelmtzinf did you manage to get to the bottom of this issue? Any progress please?

**Comment by miguelmtzinf** [comment]
@Samboy76 could you provide complete code and reproduction steps for your issue please?

**Comment by miguelmtzinf** [comment]
Closing for now. Will re-open if @Samboy76 clarifies the issue
