### ISSUE TITLE
List of all supported underlying assets for AAVE v2 and v3 flashloan 

### ISSUE THREAD

**Issue by Samboy76** [aave/aave-v3-core#849]
Hello, can you please send me the links to the v2 and v3 docs that provide me the full list of available underlying assets I can borrow Flashloans from AAVE as I cannot find it anywhere?

thank you

**Comment by miguelmtzinf** [comment]
Hi @Samboy76,
Here you can find the docs of all iterations of the protocol: https://docs.aave.com/developers/deployed-contracts/deployed-contracts
You can use the `getFlashloanEnabled` function of the [AavePoolDataProvider](https://etherscan.io/address/0x7B4EB56E7CD4b454BA8ff71E4518426369a138a3#readContract) contract to query if a given reserve is flashloanable.

**Comment by Samboy76** [comment]
Is it also available this getFlashLoanEnabled  method on Arbitrum? It seems this feature is only available on Ethereum. If not, is there an alternative similar approach for Arbitrum?
