### ISSUE TITLE
IVariableDebtToken is not inheriting IERC20 implementation

### ISSUE THREAD

**Issue by TomasCImach** [aave/aave-v3-core#902]
Looks like `VariableDebtToken.sol` does have the `ERC20` methods, but the `IVariableDebtToken.sol` does not inherit them.

Is this intentional?

How can I on-chain query the amount of borrowed tokens I need to repay to close the entire loan?

**Comment by miguelmtzinf** [comment]
Hey @TomasCImach , you can use the standard interface for ERC20 to query the outstanding debt of your position (`balanceOf` function).

**Comment by TomasCImach** [comment]
Thanks! Any reason ERC20 interface was left out of IVariableDebtToken.sol?

**Comment by miguelmtzinf** [comment]
Not specifically, the inheritance chain of aToken/debtTokens are kinda tricky and this went unnoticed.

**Comment by miguelmtzinf** [comment]
As a note, you can use a value higher than your current debt to fully repay your loan. In Solidity you can use `uint256(-1)` or `type(uint256).max` as values for that. In case of using ethers.js, just use `ethers.constants.MaxUint256`. 

You can find more information about the `repay` function in the [Aave Docs](https://docs.aave.com/developers/core-contracts/pool#repay).
