### ISSUE TITLE
[docs] Utilisation Rate wiki page leads to a 404 page

### ISSUE THREAD

**Issue by StErMi** [aave/aave-v3-core#914]
If you go over the [Borrow Interest Rate](https://docs.aave.com/risk/liquidity-risk/borrow-interest-rate) and you try to click on the "Utilisation Rate" link at the very beginning of the text, it will lead to a non-existing page.

The link used is this one: https://github.com/aave/risk-v3/blob/main/liquidity-risk/historical-utilization.md

**Comment by miguelmtzinf** [comment]
Good call @StErMi 
this seems fixed to me, could you check again so we can close this issue?

**Comment by StErMi** [comment]
@miguelmtzinf the "Utilisation Rate" now is not a link anymore. The issue has been "fixed" because not being a link, it won't redirect to an not existing page.

To be clear, when I created the issue, the main idea was that Aave would have created such page and not removed the link

**Comment by miguelmtzinf** [comment]
That page is no longer active, so link is not needed. Thanks for spotting!
