### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by jtfirek** [aave/aave-v3-core#960]
Is there a place in the documentation that has the description of each error?
```
    │   │   │   └─ ← [Revert] 0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000023336000000000000000000000000000000000000000000000000000000000000
    │   │   └─ ← [Revert] revert: 36
    │   └─ ← [Revert] revert: 36
```

**Comment by Liberalite** [comment]
COLLATERAL_CANNOT_COVER_NEW_BORROW = '36'; // 'There is not enough collateral to cover anew borrow'

You can find all AAVE V3 error codes here:

https://mirror.xyz/unfrigginbelievable.eth/fzvIBwJZQKOP4sNpkrVZGOJEk5cDr6tarimQHTw6C84

**Comment by jtfirek** [comment]
Cool thanks
